export const ORGS = [
  { value: "100 Thieves", label: "100 Thieves" },
  { value: "CLG", label: "CLG" },
  { value: "Cloud9", label: "Cloud9" },
  { value: "Complexity", label: "Complexity" },
  { value: "Dignitas", label: "Dignitas" },
  { value: "Evil Geniuses", label: "Evil Geniuses" },
  { value: "Excel", label: "Excel" },
  { value: "Fnatic", label: "Fnatic" },
  { value: "G2", label: "G2" },
  { value: "Golden Guardians", label: "Golden Guardians" },
  { value: "Guild Esports", label: "Guild Esports" },
  { value: "Heroic", label: "Heroic" },
  { value: "Immortals", label: "Immortals" },
  { value: "Ninjas in Pyjamas", label: "Ninjas in Pyjamas" },
  { value: "OverActive Media", label: "OverActive Media" },
  { value: "ReKTGlobal", label: "ReKTGlobal" },
  { value: "Riot", label: "Riot Games" },
  { value: "Team Liquid", label: "Team Liquid" },
  { value: "TSM", label: "TSM" },
  { value: "Version1", label: "Version1" },
  { value: "Vitality", label: "Vitality" },
];
